workflows:
  capacitor-android:
    name: Capacitor Android Build
    max_build_duration: 60
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android release
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
