workflows:
  capacitor-ios:
    name: Capacitor iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: codemagic

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.getchaospay.app

      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APPLE_ID: 6739287109

      node: 20
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: cd ios/App && pod install

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.getchaospay.app --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true


  capacitor-android:
    name: Capacitor Android Build
    max_build_duration: 60

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Build Android release
        script: cd android && ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab
